### ISSUE TITLE
Add support for 'INSERT ... ON DUPLICATE KEY UPDATE'

### ISSUE THREAD

**Issue by chaitanyagpt21** [doxout/anydb-sql#6]
It would be great if you could add a case for mysql 'INSERT' query with 'ON DUPLICATE KEY UPDATE' clause. It comes in very handy for updating already inserted values without adding a special case for them.

**Comment by spion** [comment]
@chaitanyagpt21 - when the feature is added to [node-sql](https://github.com/brianc/node-sql), it will automatically be available in anydb-sql aswell :) You can post to their issue tracker

**Comment by chaitanyagpt21** [comment]
Thanks @spion 
I just checked this issue is already open in node-sql. I will catch up with that.
