### ISSUE TITLE
selectDeep seems to be broken for one-to-many relationships

### ISSUE THREAD

**Issue by Goldsmith42** [doxout/anydb-sql#7]
If a table has a defined one-to-many relationship with another table via `{ has: { otherEntities: { from: 'OtherTable', many: true } } }`, selectDeep fails if the other table is passed as a property of the first table.

**Comment by spion** [comment]
selectDeep should be deprecated; however, whats the nature of the failure? Any error messages? Whats the shape of the data?

**Comment by Goldsmith42** [comment]
The query itself is malformed. It seems to be trying to use `MainTable.otherEntities[]` as an identifier. I should be able to get an error message tomorrow.

**Comment by Goldsmith42** [comment]
The issue was that me and my lack of sleep failed to notice that `OtherTable` was missing in the FROM clause.
